import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import "./style/global.scss"
import { ReduxProvider } from './redux/provider/ReduxProvider'
import Header from './components/header/Header'
import Footer from './components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Netflix',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <ReduxProvider>{children}</ReduxProvider>
        <Footer/>
      </body>
    </html>
  )
}
